### ISSUE TITLE
Evaluation of parameters are in the wrong order

### ISSUE THREAD

**Issue by kmodexc** [Backseating-Committee-2k/Seatbelt#1]
Mal frei zitiert:

Und Bug 2 ist (glaube ich) ein Logikfehler an deiner Lieblingscodestelle: 
https://github.com/Backseating-Committee-2k/Seatbelt/blob/68f6f7863b7adab74b00538238f9b8ab109d999c/emitter.cpp#L250-L256 Wenn ich das richtig verstehe, wird der Callee nach den Parametern ausgewertet, das würde dann bei a()(b()) b vor a aufrufen, oder nicht?

**Comment by mgerhold** [comment]
fixed in #34
